import Foundation

// ======================== Full app localization — all languages ========================
// Keys are English strings (the `en` parameter of store.t(vi, en)).
// Add translations for each language code here.

struct L10n {
    static func translate(_ en: String, to lang: String) -> String? {
        translations[lang]?[en]
    }

    static let translations: [String: [String: String]] = [

        // ──────────────── Chinese (Simplified) ────────────────
        "zh": [
            // —— Đăng nhập/Ví/Thanh toán (đợt 3) ——
            "Password": "密码",
            "Forgot password?": "忘记密码？",
            "or": "或",
            "Create new account": "创建新账户",
            "Create account": "创建账户",
            "Change": "更改",
            "Server": "服务器",
            "Change password": "修改密码",
            "Top up wallet": "充值钱包",
            "Wallet history": "钱包记录",
            "Purchase": "购买",
            "Bank": "银行",
            "Account number": "账号",
            "Account holder": "账户名",
            "Transfer note": "转账备注",
            "Amount": "金额",
            "Upgrade to PRO": "升级 PRO",
            "Upgrade to Pro": "升级 Pro",
            "Pro feature": "Pro 功能",
            "Pending": "待确认",
            "Credited": "已入账",
            "Username": "用户名",
            // —— Cửa hàng & Cài đặt (đợt 2) ——
            "Store wallet": "商店钱包",
            "Wallet balance": "钱包余额",
            "Downloads": "下载",
            "Download": "下载",
            "All products": "全部商品",
            "Sort": "排序",
            "Filter": "筛选",
            "Default": "默认",
            "In stock only": "仅有货",
            "Out of stock": "缺货",
            "Wishlist": "收藏",
            "Recently viewed": "最近浏览",
            "Add to cart": "加入购物车",
            "Total": "合计",
            "Subtotal": "小计",
            "Pay": "支付",
            "Promo code": "优惠码",
            "Apply": "应用",
            "My orders": "我的订单",
            "Account": "账户",
            "Status": "状态",
            "Plan": "套餐",
            "Save changes": "保存更改",
            "Choose a plan": "选择套餐",
            "Rate this product": "评价商品",
            "Contact seller": "联系卖家",
            // —— Bổ sung đa ngôn ngữ (đợt 1) ——
            "Reels": "短视频",
            "Follow": "关注",
            "Following": "已关注",
            "New video": "新视频",
            "Post video": "发布视频",
            "Description": "描述",
            "Choose video": "选择视频",
            "Add friend": "加好友",
            "Accept": "接受",
            "Decline": "拒绝",
            "Request sent": "已发送请求",
            "Your ID": "你的 ID",
            "No friends yet": "还没有好友",
            "Tap to message": "点击发消息",
            "Requests": "请求",
            "Media Converter": "媒体转换",
            "Create link": "创建链接",
            "Result link": "结果链接",
            "Format": "格式",
            "Output format": "输出格式",
            "Guide": "指南",
            "Link history": "链接历史",
            "Clear all": "全部清除",
            "Choose image or video": "选择图片或视频",
            "Uploading...": "上传中...",
            "Processing...": "处理中...",
            // Navigation / Tab bar
            "Social":               "社交",
            "Video":                "视频",
            "Store":                "商店",
            "Friends":              "朋友",
            "Explore":              "探索",
            // Common buttons
            "Login":                "登录",
            "Register":             "注册",
            "Save":                 "保存",
            "Cancel":               "取消",
            "Delete":               "删除",
            "Edit":                 "编辑",
            "Close":                "关闭",
            "Back":                 "返回",
            "Done":                 "完成",
            "Confirm":              "确认",
            "Search":               "搜索",
            "Send":                 "发送",
            "Add":                  "添加",
            "Remove":               "删除",
            "Share":                "分享",
            "Copy":                 "复制",
            "Logout":               "退出",
            "Settings":             "设置",
            "Admin":                "管理",
            "Profile":              "资料",
            "Home":                 "主页",
            "Next":                 "下一步",
            "Continue":             "继续",
            "Retry":                "重试",
            // Settings
            "Language & Appearance": "语言与外观",
            "Language":             "语言",
            "Theme":                "主题",
            "Light":                "浅色",
            "Dark":                 "深色",
            "Auto":                 "自动",
            "App logo & effects":   "应用图标与效果",
            "Color effect":         "颜色效果",
            "Font":                 "字体",
            "Animation":            "动画",
            // Store
            "Cart":                 "购物车",
            "Checkout":             "结账",
            "Buy":                  "购买",
            "Price":                "价格",
            "Discount":             "折扣",
            "Product":              "商品",
            "Category":             "分类",
            "Order":                "订单",
            "Payment":              "付款",
            "Balance":              "余额",
            "Wallet":               "钱包",
            "Top up":               "充值",
            "Purchase history":     "购买记录",
            "Review":               "评价",
            "Rating":               "评分",
            // Status
            "Loading...":           "加载中...",
            "Error":                "错误",
            "Success":              "成功",
            "Failed":               "失败",
            "Connecting...":        "连接中...",
            "Connected":            "已连接",
            "Disconnected":         "已断开",
            // Friends / Social
            "Friends":              "朋友",
            "Messages":             "消息",
            "Notifications":        "通知",
            "Online":               "在线",
            "Offline":              "离线",
            // Misc
            "Entertainment":        "娱乐",
            "Library":              "库",
            "Tools":                "工具",
            "Games":                "游戏",
            "Converter":            "转换器",
        ],

        // ──────────────── Korean ────────────────
        "ko": [
            // —— Đăng nhập/Ví/Thanh toán (đợt 3) ——
            "Password": "비밀번호",
            "Forgot password?": "비밀번호 찾기?",
            "or": "또는",
            "Create new account": "새 계정 만들기",
            "Create account": "계정 만들기",
            "Change": "변경",
            "Server": "서버",
            "Change password": "비밀번호 변경",
            "Top up wallet": "지갑 충전",
            "Wallet history": "지갑 내역",
            "Purchase": "구매",
            "Bank": "은행",
            "Account number": "계좌번호",
            "Account holder": "예금주",
            "Transfer note": "이체 메모",
            "Amount": "금액",
            "Upgrade to PRO": "PRO 업그레이드",
            "Upgrade to Pro": "Pro 업그레이드",
            "Pro feature": "Pro 기능",
            "Pending": "대기 중",
            "Credited": "입금됨",
            "Username": "사용자 이름",
            // —— Cửa hàng & Cài đặt (đợt 2) ——
            "Store wallet": "상점 지갑",
            "Wallet balance": "지갑 잔액",
            "Downloads": "다운로드",
            "Download": "다운로드",
            "All products": "모든 상품",
            "Sort": "정렬",
            "Filter": "필터",
            "Default": "기본",
            "In stock only": "재고만",
            "Out of stock": "품절",
            "Wishlist": "위시리스트",
            "Recently viewed": "최근 본",
            "Add to cart": "장바구니 담기",
            "Total": "합계",
            "Subtotal": "소계",
            "Pay": "결제",
            "Promo code": "프로모션 코드",
            "Apply": "적용",
            "My orders": "내 주문",
            "Account": "계정",
            "Status": "상태",
            "Plan": "플랜",
            "Save changes": "변경 저장",
            "Choose a plan": "플랜 선택",
            "Rate this product": "상품 평가",
            "Contact seller": "판매자 문의",
            // —— Bổ sung đa ngôn ngữ (đợt 1) ——
            "Reels": "릴스",
            "Follow": "팔로우",
            "Following": "팔로잉",
            "New video": "새 동영상",
            "Post video": "동영상 게시",
            "Description": "설명",
            "Choose video": "동영상 선택",
            "Add friend": "친구 추가",
            "Accept": "수락",
            "Decline": "거절",
            "Request sent": "요청 보냄",
            "Your ID": "내 ID",
            "No friends yet": "아직 친구가 없습니다",
            "Tap to message": "눌러서 메시지",
            "Requests": "요청",
            "Media Converter": "미디어 변환",
            "Create link": "링크 생성",
            "Result link": "결과 링크",
            "Format": "형식",
            "Output format": "출력 형식",
            "Guide": "가이드",
            "Link history": "링크 기록",
            "Clear all": "모두 지우기",
            "Choose image or video": "이미지 또는 동영상 선택",
            "Uploading...": "업로드 중...",
            "Processing...": "처리 중...",
            "Social":               "소셜",
            "Video":                "비디오",
            "Store":                "스토어",
            "Friends":              "친구",
            "Explore":              "탐색",
            "Login":                "로그인",
            "Register":             "회원가입",
            "Save":                 "저장",
            "Cancel":               "취소",
            "Delete":               "삭제",
            "Edit":                 "편집",
            "Close":                "닫기",
            "Back":                 "뒤로",
            "Done":                 "완료",
            "Confirm":              "확인",
            "Search":               "검색",
            "Send":                 "보내기",
            "Add":                  "추가",
            "Remove":               "제거",
            "Share":                "공유",
            "Copy":                 "복사",
            "Logout":               "로그아웃",
            "Settings":             "설정",
            "Admin":                "관리자",
            "Profile":              "프로필",
            "Home":                 "홈",
            "Next":                 "다음",
            "Continue":             "계속",
            "Retry":                "다시 시도",
            "Language & Appearance": "언어 및 외관",
            "Language":             "언어",
            "Theme":                "테마",
            "Light":                "라이트",
            "Dark":                 "다크",
            "Auto":                 "자동",
            "App logo & effects":   "앱 로고 및 효과",
            "Color effect":         "색상 효과",
            "Font":                 "폰트",
            "Animation":            "애니메이션",
            "Cart":                 "장바구니",
            "Checkout":             "결제",
            "Buy":                  "구매",
            "Price":                "가격",
            "Discount":             "할인",
            "Product":              "상품",
            "Category":             "카테고리",
            "Order":                "주문",
            "Payment":              "결제",
            "Balance":              "잔액",
            "Wallet":               "지갑",
            "Top up":               "충전",
            "Purchase history":     "구매 내역",
            "Review":               "리뷰",
            "Rating":               "평점",
            "Loading...":           "로딩 중...",
            "Error":                "오류",
            "Success":              "성공",
            "Failed":               "실패",
            "Connecting...":        "연결 중...",
            "Connected":            "연결됨",
            "Disconnected":         "연결 해제됨",
            "Friends":              "친구",
            "Messages":             "메시지",
            "Notifications":        "알림",
            "Online":               "온라인",
            "Offline":              "오프라인",
            "Entertainment":        "엔터테인먼트",
            "Library":              "라이브러리",
            "Tools":                "도구",
            "Games":                "게임",
            "Converter":            "변환기",
        ],

        // ──────────────── Japanese ────────────────
        "ja": [
            // —— Đăng nhập/Ví/Thanh toán (đợt 3) ——
            "Password": "パスワード",
            "Forgot password?": "パスワードを忘れた？",
            "or": "または",
            "Create new account": "新規アカウント作成",
            "Create account": "アカウント作成",
            "Change": "変更",
            "Server": "サーバー",
            "Change password": "パスワード変更",
            "Top up wallet": "ウォレット入金",
            "Wallet history": "ウォレット履歴",
            "Purchase": "購入",
            "Bank": "銀行",
            "Account number": "口座番号",
            "Account holder": "口座名義",
            "Transfer note": "振込メモ",
            "Amount": "金額",
            "Upgrade to PRO": "PROにアップグレード",
            "Upgrade to Pro": "Proにアップグレード",
            "Pro feature": "Pro機能",
            "Pending": "保留中",
            "Credited": "入金済み",
            "Username": "ユーザー名",
            // —— Cửa hàng & Cài đặt (đợt 2) ——
            "Store wallet": "ストアウォレット",
            "Wallet balance": "残高",
            "Downloads": "ダウンロード",
            "Download": "ダウンロード",
            "All products": "すべての商品",
            "Sort": "並び替え",
            "Filter": "フィルター",
            "Default": "デフォルト",
            "In stock only": "在庫ありのみ",
            "Out of stock": "在庫切れ",
            "Wishlist": "お気に入り",
            "Recently viewed": "最近見た",
            "Add to cart": "カートに追加",
            "Total": "合計",
            "Subtotal": "小計",
            "Pay": "支払う",
            "Promo code": "プロモコード",
            "Apply": "適用",
            "My orders": "注文履歴",
            "Account": "アカウント",
            "Status": "状態",
            "Plan": "プラン",
            "Save changes": "変更を保存",
            "Choose a plan": "プランを選択",
            "Rate this product": "商品を評価",
            "Contact seller": "出品者に連絡",
            // —— Bổ sung đa ngôn ngữ (đợt 1) ——
            "Reels": "リール",
            "Follow": "フォロー",
            "Following": "フォロー中",
            "New video": "新しい動画",
            "Post video": "動画を投稿",
            "Description": "説明",
            "Choose video": "動画を選択",
            "Add friend": "友達を追加",
            "Accept": "承認",
            "Decline": "拒否",
            "Request sent": "リクエスト送信済み",
            "Your ID": "あなたのID",
            "No friends yet": "まだ友達がいません",
            "Tap to message": "タップしてメッセージ",
            "Requests": "リクエスト",
            "Media Converter": "メディア変換",
            "Create link": "リンク作成",
            "Result link": "結果リンク",
            "Format": "形式",
            "Output format": "出力形式",
            "Guide": "ガイド",
            "Link history": "リンク履歴",
            "Clear all": "すべて消去",
            "Choose image or video": "画像か動画を選択",
            "Uploading...": "アップロード中...",
            "Processing...": "処理中...",
            "Social":               "ソーシャル",
            "Video":                "ビデオ",
            "Store":                "ストア",
            "Friends":              "友達",
            "Explore":              "探索",
            "Login":                "ログイン",
            "Register":             "登録",
            "Save":                 "保存",
            "Cancel":               "キャンセル",
            "Delete":               "削除",
            "Edit":                 "編集",
            "Close":                "閉じる",
            "Back":                 "戻る",
            "Done":                 "完了",
            "Confirm":              "確認",
            "Search":               "検索",
            "Send":                 "送信",
            "Add":                  "追加",
            "Remove":               "削除",
            "Share":                "シェア",
            "Copy":                 "コピー",
            "Logout":               "ログアウト",
            "Settings":             "設定",
            "Admin":                "管理",
            "Profile":              "プロフィール",
            "Home":                 "ホーム",
            "Next":                 "次へ",
            "Continue":             "続ける",
            "Retry":                "再試行",
            "Language & Appearance": "言語と外観",
            "Language":             "言語",
            "Theme":                "テーマ",
            "Light":                "ライト",
            "Dark":                 "ダーク",
            "Auto":                 "自動",
            "App logo & effects":   "アプリロゴとエフェクト",
            "Color effect":         "カラーエフェクト",
            "Font":                 "フォント",
            "Animation":            "アニメーション",
            "Cart":                 "カート",
            "Checkout":             "チェックアウト",
            "Buy":                  "購入",
            "Price":                "価格",
            "Discount":             "割引",
            "Product":              "商品",
            "Category":             "カテゴリ",
            "Order":                "注文",
            "Payment":              "支払い",
            "Balance":              "残高",
            "Wallet":               "ウォレット",
            "Top up":               "チャージ",
            "Purchase history":     "購入履歴",
            "Review":               "レビュー",
            "Rating":               "評価",
            "Loading...":           "読み込み中...",
            "Error":                "エラー",
            "Success":              "成功",
            "Failed":               "失敗",
            "Connecting...":        "接続中...",
            "Connected":            "接続済み",
            "Disconnected":         "切断済み",
            "Messages":             "メッセージ",
            "Notifications":        "通知",
            "Online":               "オンライン",
            "Offline":              "オフライン",
            "Entertainment":        "エンタメ",
            "Library":              "ライブラリ",
            "Tools":                "ツール",
            "Games":                "ゲーム",
            "Converter":            "コンバーター",
        ],

        // ──────────────── Thai ────────────────
        "th": [
            // —— Đăng nhập/Ví/Thanh toán (đợt 3) ——
            "Password": "รหัสผ่าน",
            "Forgot password?": "ลืมรหัสผ่าน?",
            "or": "หรือ",
            "Create new account": "สร้างบัญชีใหม่",
            "Create account": "สร้างบัญชี",
            "Change": "เปลี่ยน",
            "Server": "เซิร์ฟเวอร์",
            "Change password": "เปลี่ยนรหัสผ่าน",
            "Top up wallet": "เติมเงินกระเป๋า",
            "Wallet history": "ประวัติกระเป๋า",
            "Purchase": "ซื้อ",
            "Bank": "ธนาคาร",
            "Account number": "เลขบัญชี",
            "Account holder": "ชื่อบัญชี",
            "Transfer note": "หมายเหตุโอน",
            "Amount": "จำนวนเงิน",
            "Upgrade to PRO": "อัปเกรด PRO",
            "Upgrade to Pro": "อัปเกรด Pro",
            "Pro feature": "ฟีเจอร์ Pro",
            "Pending": "รอดำเนินการ",
            "Credited": "เข้าบัญชีแล้ว",
            "Username": "ชื่อผู้ใช้",
            // —— Cửa hàng & Cài đặt (đợt 2) ——
            "Store wallet": "กระเป๋าร้าน",
            "Wallet balance": "ยอดเงิน",
            "Downloads": "ดาวน์โหลด",
            "Download": "ดาวน์โหลด",
            "All products": "สินค้าทั้งหมด",
            "Sort": "จัดเรียง",
            "Filter": "กรอง",
            "Default": "ค่าเริ่มต้น",
            "In stock only": "เฉพาะมีสินค้า",
            "Out of stock": "สินค้าหมด",
            "Wishlist": "รายการโปรด",
            "Recently viewed": "ดูล่าสุด",
            "Add to cart": "ใส่ตะกร้า",
            "Total": "รวม",
            "Subtotal": "ยอดรวมย่อย",
            "Pay": "ชำระเงิน",
            "Promo code": "โค้ดส่วนลด",
            "Apply": "ใช้",
            "My orders": "คำสั่งซื้อของฉัน",
            "Account": "บัญชี",
            "Status": "สถานะ",
            "Plan": "แพ็กเกจ",
            "Save changes": "บันทึกการเปลี่ยนแปลง",
            "Choose a plan": "เลือกแพ็กเกจ",
            "Rate this product": "ให้คะแนนสินค้า",
            "Contact seller": "ติดต่อผู้ขาย",
            // —— Bổ sung đa ngôn ngữ (đợt 1) ——
            "Reels": "รีลส์",
            "Follow": "ติดตาม",
            "Following": "กำลังติดตาม",
            "New video": "วิดีโอใหม่",
            "Post video": "โพสต์วิดีโอ",
            "Description": "คำอธิบาย",
            "Choose video": "เลือกวิดีโอ",
            "Add friend": "เพิ่มเพื่อน",
            "Accept": "ยอมรับ",
            "Decline": "ปฏิเสธ",
            "Request sent": "ส่งคำขอแล้ว",
            "Your ID": "ID ของคุณ",
            "No friends yet": "ยังไม่มีเพื่อน",
            "Tap to message": "แตะเพื่อส่งข้อความ",
            "Requests": "คำขอ",
            "Media Converter": "แปลงสื่อ",
            "Create link": "สร้างลิงก์",
            "Result link": "ลิงก์ผลลัพธ์",
            "Format": "รูปแบบ",
            "Output format": "รูปแบบผลลัพธ์",
            "Guide": "คู่มือ",
            "Link history": "ประวัติลิงก์",
            "Clear all": "ล้างทั้งหมด",
            "Choose image or video": "เลือกรูปหรือวิดีโอ",
            "Uploading...": "กำลังอัปโหลด...",
            "Processing...": "กำลังประมวลผล...",
            "Social":               "โซเชียล",
            "Video":                "วิดีโอ",
            "Store":                "ร้านค้า",
            "Friends":              "เพื่อน",
            "Explore":              "สำรวจ",
            "Login":                "เข้าสู่ระบบ",
            "Register":             "สมัครสมาชิก",
            "Save":                 "บันทึก",
            "Cancel":               "ยกเลิก",
            "Delete":               "ลบ",
            "Edit":                 "แก้ไข",
            "Close":                "ปิด",
            "Back":                 "กลับ",
            "Done":                 "เสร็จ",
            "Confirm":              "ยืนยัน",
            "Search":               "ค้นหา",
            "Send":                 "ส่ง",
            "Add":                  "เพิ่ม",
            "Remove":               "ลบออก",
            "Share":                "แชร์",
            "Copy":                 "คัดลอก",
            "Logout":               "ออกจากระบบ",
            "Settings":             "ตั้งค่า",
            "Admin":                "ผู้ดูแล",
            "Profile":              "โปรไฟล์",
            "Home":                 "หน้าหลัก",
            "Next":                 "ถัดไป",
            "Continue":             "ต่อไป",
            "Retry":                "ลองอีกครั้ง",
            "Language & Appearance": "ภาษาและรูปลักษณ์",
            "Language":             "ภาษา",
            "Theme":                "ธีม",
            "Light":                "สว่าง",
            "Dark":                 "มืด",
            "Auto":                 "อัตโนมัติ",
            "App logo & effects":   "โลโก้และเอฟเฟกต์",
            "Color effect":         "เอฟเฟกต์สี",
            "Font":                 "แบบอักษร",
            "Animation":            "แอนิเมชัน",
            "Cart":                 "ตะกร้า",
            "Checkout":             "ชำระเงิน",
            "Buy":                  "ซื้อ",
            "Price":                "ราคา",
            "Discount":             "ส่วนลด",
            "Product":              "สินค้า",
            "Category":             "หมวดหมู่",
            "Order":                "คำสั่งซื้อ",
            "Payment":              "การชำระเงิน",
            "Balance":              "ยอดเงิน",
            "Wallet":               "กระเป๋าเงิน",
            "Top up":               "เติมเงิน",
            "Purchase history":     "ประวัติการซื้อ",
            "Review":               "รีวิว",
            "Rating":               "คะแนน",
            "Loading...":           "กำลังโหลด...",
            "Error":                "ข้อผิดพลาด",
            "Success":              "สำเร็จ",
            "Failed":               "ล้มเหลว",
            "Connecting...":        "กำลังเชื่อมต่อ...",
            "Connected":            "เชื่อมต่อแล้ว",
            "Disconnected":         "ตัดการเชื่อมต่อ",
            "Messages":             "ข้อความ",
            "Notifications":        "การแจ้งเตือน",
            "Online":               "ออนไลน์",
            "Offline":              "ออฟไลน์",
            "Entertainment":        "ความบันเทิง",
            "Library":              "ไลบรารี",
            "Tools":                "เครื่องมือ",
            "Games":                "เกม",
            "Converter":            "ตัวแปลง",
        ],

        // ──────────────── French ────────────────
        "fr": [
            // —— Đăng nhập/Ví/Thanh toán (đợt 3) ——
            "Password": "Mot de passe",
            "Forgot password?": "Mot de passe oublié ?",
            "or": "ou",
            "Create new account": "Créer un compte",
            "Create account": "Créer un compte",
            "Change": "Changer",
            "Server": "Serveur",
            "Change password": "Changer le mot de passe",
            "Top up wallet": "Recharger le portefeuille",
            "Wallet history": "Historique",
            "Purchase": "Achat",
            "Bank": "Banque",
            "Account number": "Numéro de compte",
            "Account holder": "Titulaire",
            "Transfer note": "Note de virement",
            "Amount": "Montant",
            "Upgrade to PRO": "Passer à PRO",
            "Upgrade to Pro": "Passer à Pro",
            "Pro feature": "Fonction Pro",
            "Pending": "En attente",
            "Credited": "Crédité",
            "Username": "Nom d'utilisateur",
            // —— Cửa hàng & Cài đặt (đợt 2) ——
            "Store wallet": "Portefeuille",
            "Wallet balance": "Solde",
            "Downloads": "Téléchargements",
            "Download": "Télécharger",
            "All products": "Tous les produits",
            "Sort": "Trier",
            "Filter": "Filtrer",
            "Default": "Par défaut",
            "In stock only": "En stock seulement",
            "Out of stock": "Épuisé",
            "Wishlist": "Favoris",
            "Recently viewed": "Vu récemment",
            "Add to cart": "Ajouter au panier",
            "Total": "Total",
            "Subtotal": "Sous-total",
            "Pay": "Payer",
            "Promo code": "Code promo",
            "Apply": "Appliquer",
            "My orders": "Mes commandes",
            "Account": "Compte",
            "Status": "Statut",
            "Plan": "Forfait",
            "Save changes": "Enregistrer",
            "Choose a plan": "Choisir un forfait",
            "Rate this product": "Noter le produit",
            "Contact seller": "Contacter le vendeur",
            // —— Bổ sung đa ngôn ngữ (đợt 1) ——
            "Reels": "Reels",
            "Follow": "Suivre",
            "Following": "Abonné",
            "New video": "Nouvelle vidéo",
            "Post video": "Publier la vidéo",
            "Description": "Description",
            "Choose video": "Choisir une vidéo",
            "Add friend": "Ajouter un ami",
            "Accept": "Accepter",
            "Decline": "Refuser",
            "Request sent": "Demande envoyée",
            "Your ID": "Votre ID",
            "No friends yet": "Pas encore d'amis",
            "Tap to message": "Toucher pour écrire",
            "Requests": "Demandes",
            "Media Converter": "Convertisseur média",
            "Create link": "Créer le lien",
            "Result link": "Lien résultat",
            "Format": "Format",
            "Output format": "Format de sortie",
            "Guide": "Guide",
            "Link history": "Historique des liens",
            "Clear all": "Tout effacer",
            "Choose image or video": "Choisir image ou vidéo",
            "Uploading...": "Téléversement...",
            "Processing...": "Traitement...",
            "Social":               "Social",
            "Video":                "Vidéo",
            "Store":                "Boutique",
            "Friends":              "Amis",
            "Explore":              "Explorer",
            "Login":                "Connexion",
            "Register":             "Inscription",
            "Save":                 "Enregistrer",
            "Cancel":               "Annuler",
            "Delete":               "Supprimer",
            "Edit":                 "Modifier",
            "Close":                "Fermer",
            "Back":                 "Retour",
            "Done":                 "Terminer",
            "Confirm":              "Confirmer",
            "Search":               "Rechercher",
            "Send":                 "Envoyer",
            "Add":                  "Ajouter",
            "Remove":               "Retirer",
            "Share":                "Partager",
            "Copy":                 "Copier",
            "Logout":               "Déconnexion",
            "Settings":             "Paramètres",
            "Admin":                "Admin",
            "Profile":              "Profil",
            "Home":                 "Accueil",
            "Next":                 "Suivant",
            "Continue":             "Continuer",
            "Retry":                "Réessayer",
            "Language & Appearance": "Langue et apparence",
            "Language":             "Langue",
            "Theme":                "Thème",
            "Light":                "Clair",
            "Dark":                 "Sombre",
            "Auto":                 "Auto",
            "App logo & effects":   "Logo et effets",
            "Color effect":         "Effet couleur",
            "Font":                 "Police",
            "Animation":            "Animation",
            "Cart":                 "Panier",
            "Checkout":             "Paiement",
            "Buy":                  "Acheter",
            "Price":                "Prix",
            "Discount":             "Réduction",
            "Product":              "Produit",
            "Category":             "Catégorie",
            "Order":                "Commande",
            "Payment":              "Paiement",
            "Balance":              "Solde",
            "Wallet":               "Portefeuille",
            "Top up":               "Recharger",
            "Purchase history":     "Historique",
            "Review":               "Avis",
            "Rating":               "Note",
            "Loading...":           "Chargement...",
            "Error":                "Erreur",
            "Success":              "Succès",
            "Failed":               "Échec",
            "Connecting...":        "Connexion...",
            "Connected":            "Connecté",
            "Disconnected":         "Déconnecté",
            "Messages":             "Messages",
            "Notifications":        "Notifications",
            "Online":               "En ligne",
            "Offline":              "Hors ligne",
            "Entertainment":        "Divertissement",
            "Library":              "Bibliothèque",
            "Tools":                "Outils",
            "Games":                "Jeux",
            "Converter":            "Convertisseur",
        ],

        // ──────────────── Spanish ────────────────
        "es": [
            // —— Đăng nhập/Ví/Thanh toán (đợt 3) ——
            "Password": "Contraseña",
            "Forgot password?": "¿Olvidó la contraseña?",
            "or": "o",
            "Create new account": "Crear cuenta nueva",
            "Create account": "Crear cuenta",
            "Change": "Cambiar",
            "Server": "Servidor",
            "Change password": "Cambiar contraseña",
            "Top up wallet": "Recargar billetera",
            "Wallet history": "Historial",
            "Purchase": "Compra",
            "Bank": "Banco",
            "Account number": "Número de cuenta",
            "Account holder": "Titular",
            "Transfer note": "Nota de transferencia",
            "Amount": "Importe",
            "Upgrade to PRO": "Mejorar a PRO",
            "Upgrade to Pro": "Mejorar a Pro",
            "Pro feature": "Función Pro",
            "Pending": "Pendiente",
            "Credited": "Acreditado",
            "Username": "Usuario",
            // —— Cửa hàng & Cài đặt (đợt 2) ——
            "Store wallet": "Billetera",
            "Wallet balance": "Saldo",
            "Downloads": "Descargas",
            "Download": "Descargar",
            "All products": "Todos los productos",
            "Sort": "Ordenar",
            "Filter": "Filtrar",
            "Default": "Predeterminado",
            "In stock only": "Solo en stock",
            "Out of stock": "Agotado",
            "Wishlist": "Favoritos",
            "Recently viewed": "Visto recientemente",
            "Add to cart": "Añadir al carrito",
            "Total": "Total",
            "Subtotal": "Subtotal",
            "Pay": "Pagar",
            "Promo code": "Código promo",
            "Apply": "Aplicar",
            "My orders": "Mis pedidos",
            "Account": "Cuenta",
            "Status": "Estado",
            "Plan": "Plan",
            "Save changes": "Guardar cambios",
            "Choose a plan": "Elegir plan",
            "Rate this product": "Valorar producto",
            "Contact seller": "Contactar vendedor",
            // —— Bổ sung đa ngôn ngữ (đợt 1) ——
            "Reels": "Reels",
            "Follow": "Seguir",
            "Following": "Siguiendo",
            "New video": "Nuevo video",
            "Post video": "Publicar video",
            "Description": "Descripción",
            "Choose video": "Elegir video",
            "Add friend": "Añadir amigo",
            "Accept": "Aceptar",
            "Decline": "Rechazar",
            "Request sent": "Solicitud enviada",
            "Your ID": "Tu ID",
            "No friends yet": "Aún no hay amigos",
            "Tap to message": "Toca para mensaje",
            "Requests": "Solicitudes",
            "Media Converter": "Conversor de medios",
            "Create link": "Crear enlace",
            "Result link": "Enlace resultante",
            "Format": "Formato",
            "Output format": "Formato de salida",
            "Guide": "Guía",
            "Link history": "Historial de enlaces",
            "Clear all": "Borrar todo",
            "Choose image or video": "Elegir imagen o video",
            "Uploading...": "Subiendo...",
            "Processing...": "Procesando...",
            "Social":               "Social",
            "Video":                "Video",
            "Store":                "Tienda",
            "Friends":              "Amigos",
            "Explore":              "Explorar",
            "Login":                "Iniciar sesión",
            "Register":             "Registrarse",
            "Save":                 "Guardar",
            "Cancel":               "Cancelar",
            "Delete":               "Eliminar",
            "Edit":                 "Editar",
            "Close":                "Cerrar",
            "Back":                 "Atrás",
            "Done":                 "Listo",
            "Confirm":              "Confirmar",
            "Search":               "Buscar",
            "Send":                 "Enviar",
            "Add":                  "Agregar",
            "Remove":               "Quitar",
            "Share":                "Compartir",
            "Copy":                 "Copiar",
            "Logout":               "Cerrar sesión",
            "Settings":             "Ajustes",
            "Admin":                "Admin",
            "Profile":              "Perfil",
            "Home":                 "Inicio",
            "Next":                 "Siguiente",
            "Continue":             "Continuar",
            "Retry":                "Reintentar",
            "Language & Appearance": "Idioma y apariencia",
            "Language":             "Idioma",
            "Theme":                "Tema",
            "Light":                "Claro",
            "Dark":                 "Oscuro",
            "Auto":                 "Auto",
            "App logo & effects":   "Logo y efectos",
            "Color effect":         "Efecto de color",
            "Font":                 "Fuente",
            "Animation":            "Animación",
            "Cart":                 "Carrito",
            "Checkout":             "Pagar",
            "Buy":                  "Comprar",
            "Price":                "Precio",
            "Discount":             "Descuento",
            "Product":              "Producto",
            "Category":             "Categoría",
            "Order":                "Pedido",
            "Payment":              "Pago",
            "Balance":              "Saldo",
            "Wallet":               "Billetera",
            "Top up":               "Recargar",
            "Purchase history":     "Historial",
            "Review":               "Reseña",
            "Rating":               "Calificación",
            "Loading...":           "Cargando...",
            "Error":                "Error",
            "Success":              "Éxito",
            "Failed":               "Fallido",
            "Connecting...":        "Conectando...",
            "Connected":            "Conectado",
            "Disconnected":         "Desconectado",
            "Messages":             "Mensajes",
            "Notifications":        "Notificaciones",
            "Online":               "En línea",
            "Offline":              "Sin conexión",
            "Entertainment":        "Entretenimiento",
            "Library":              "Biblioteca",
            "Tools":                "Herramientas",
            "Games":                "Juegos",
            "Converter":            "Convertidor",
        ],

        // ──────────────── German ────────────────
        "de": [
            // —— Đăng nhập/Ví/Thanh toán (đợt 3) ——
            "Password": "Passwort",
            "Forgot password?": "Passwort vergessen?",
            "or": "oder",
            "Create new account": "Neues Konto erstellen",
            "Create account": "Konto erstellen",
            "Change": "Ändern",
            "Server": "Server",
            "Change password": "Passwort ändern",
            "Top up wallet": "Wallet aufladen",
            "Wallet history": "Wallet-Verlauf",
            "Purchase": "Kauf",
            "Bank": "Bank",
            "Account number": "Kontonummer",
            "Account holder": "Kontoinhaber",
            "Transfer note": "Verwendungszweck",
            "Amount": "Betrag",
            "Upgrade to PRO": "Auf PRO upgraden",
            "Upgrade to Pro": "Auf Pro upgraden",
            "Pro feature": "Pro-Funktion",
            "Pending": "Ausstehend",
            "Credited": "Gutgeschrieben",
            "Username": "Benutzername",
            // —— Cửa hàng & Cài đặt (đợt 2) ——
            "Store wallet": "Shop-Wallet",
            "Wallet balance": "Guthaben",
            "Downloads": "Downloads",
            "Download": "Herunterladen",
            "All products": "Alle Produkte",
            "Sort": "Sortieren",
            "Filter": "Filtern",
            "Default": "Standard",
            "In stock only": "Nur vorrätig",
            "Out of stock": "Ausverkauft",
            "Wishlist": "Wunschliste",
            "Recently viewed": "Kürzlich angesehen",
            "Add to cart": "In den Warenkorb",
            "Total": "Gesamt",
            "Subtotal": "Zwischensumme",
            "Pay": "Bezahlen",
            "Promo code": "Gutscheincode",
            "Apply": "Anwenden",
            "My orders": "Meine Bestellungen",
            "Account": "Konto",
            "Status": "Status",
            "Plan": "Tarif",
            "Save changes": "Änderungen speichern",
            "Choose a plan": "Tarif wählen",
            "Rate this product": "Produkt bewerten",
            "Contact seller": "Verkäufer kontaktieren",
            // —— Bổ sung đa ngôn ngữ (đợt 1) ——
            "Reels": "Reels",
            "Follow": "Folgen",
            "Following": "Abonniert",
            "New video": "Neues Video",
            "Post video": "Video posten",
            "Description": "Beschreibung",
            "Choose video": "Video wählen",
            "Add friend": "Freund hinzufügen",
            "Accept": "Annehmen",
            "Decline": "Ablehnen",
            "Request sent": "Anfrage gesendet",
            "Your ID": "Deine ID",
            "No friends yet": "Noch keine Freunde",
            "Tap to message": "Tippen zum Schreiben",
            "Requests": "Anfragen",
            "Media Converter": "Medien-Konverter",
            "Create link": "Link erstellen",
            "Result link": "Ergebnis-Link",
            "Format": "Format",
            "Output format": "Ausgabeformat",
            "Guide": "Anleitung",
            "Link history": "Link-Verlauf",
            "Clear all": "Alle löschen",
            "Choose image or video": "Bild oder Video wählen",
            "Uploading...": "Wird hochgeladen...",
            "Processing...": "Verarbeitung...",
            "Social":               "Sozial",
            "Video":                "Video",
            "Store":                "Shop",
            "Friends":              "Freunde",
            "Explore":              "Entdecken",
            "Login":                "Anmelden",
            "Register":             "Registrieren",
            "Save":                 "Speichern",
            "Cancel":               "Abbrechen",
            "Delete":               "Löschen",
            "Edit":                 "Bearbeiten",
            "Close":                "Schließen",
            "Back":                 "Zurück",
            "Done":                 "Fertig",
            "Confirm":              "Bestätigen",
            "Search":               "Suchen",
            "Send":                 "Senden",
            "Add":                  "Hinzufügen",
            "Remove":               "Entfernen",
            "Share":                "Teilen",
            "Copy":                 "Kopieren",
            "Logout":               "Abmelden",
            "Settings":             "Einstellungen",
            "Admin":                "Admin",
            "Profile":              "Profil",
            "Home":                 "Startseite",
            "Next":                 "Weiter",
            "Continue":             "Fortfahren",
            "Retry":                "Wiederholen",
            "Language & Appearance": "Sprache und Darstellung",
            "Language":             "Sprache",
            "Theme":                "Design",
            "Light":                "Hell",
            "Dark":                 "Dunkel",
            "Auto":                 "Auto",
            "App logo & effects":   "Logo und Effekte",
            "Color effect":         "Farbeffekt",
            "Font":                 "Schriftart",
            "Animation":            "Animation",
            "Cart":                 "Warenkorb",
            "Checkout":             "Kasse",
            "Buy":                  "Kaufen",
            "Price":                "Preis",
            "Discount":             "Rabatt",
            "Product":              "Produkt",
            "Category":             "Kategorie",
            "Order":                "Bestellung",
            "Payment":              "Zahlung",
            "Balance":              "Guthaben",
            "Wallet":               "Geldbörse",
            "Top up":               "Aufladen",
            "Purchase history":     "Kaufhistorie",
            "Review":               "Bewertung",
            "Rating":               "Bewertung",
            "Loading...":           "Laden...",
            "Error":                "Fehler",
            "Success":              "Erfolg",
            "Failed":               "Fehlgeschlagen",
            "Connecting...":        "Verbinden...",
            "Connected":            "Verbunden",
            "Disconnected":         "Getrennt",
            "Messages":             "Nachrichten",
            "Notifications":        "Benachrichtigungen",
            "Online":               "Online",
            "Offline":              "Offline",
            "Entertainment":        "Unterhaltung",
            "Library":              "Bibliothek",
            "Tools":                "Werkzeuge",
            "Games":                "Spiele",
            "Converter":            "Konverter",
        ],

        // ──────────────── Portuguese ────────────────
        "pt": [
            // —— Đăng nhập/Ví/Thanh toán (đợt 3) ——
            "Password": "Senha",
            "Forgot password?": "Esqueceu a senha?",
            "or": "ou",
            "Create new account": "Criar nova conta",
            "Create account": "Criar conta",
            "Change": "Alterar",
            "Server": "Servidor",
            "Change password": "Alterar senha",
            "Top up wallet": "Recarregar carteira",
            "Wallet history": "Histórico da carteira",
            "Purchase": "Compra",
            "Bank": "Banco",
            "Account number": "Número da conta",
            "Account holder": "Titular",
            "Transfer note": "Descrição",
            "Amount": "Valor",
            "Upgrade to PRO": "Mudar para PRO",
            "Upgrade to Pro": "Mudar para Pro",
            "Pro feature": "Recurso Pro",
            "Pending": "Pendente",
            "Credited": "Creditado",
            "Username": "Usuário",
            // —— Cửa hàng & Cài đặt (đợt 2) ——
            "Store wallet": "Carteira",
            "Wallet balance": "Saldo",
            "Downloads": "Downloads",
            "Download": "Baixar",
            "All products": "Todos os produtos",
            "Sort": "Ordenar",
            "Filter": "Filtrar",
            "Default": "Padrão",
            "In stock only": "Só em estoque",
            "Out of stock": "Esgotado",
            "Wishlist": "Favoritos",
            "Recently viewed": "Vistos recentemente",
            "Add to cart": "Adicionar ao carrinho",
            "Total": "Total",
            "Subtotal": "Subtotal",
            "Pay": "Pagar",
            "Promo code": "Código promo",
            "Apply": "Aplicar",
            "My orders": "Meus pedidos",
            "Account": "Conta",
            "Status": "Estado",
            "Plan": "Plano",
            "Save changes": "Salvar alterações",
            "Choose a plan": "Escolher plano",
            "Rate this product": "Avaliar produto",
            "Contact seller": "Contatar vendedor",
            // —— Bổ sung đa ngôn ngữ (đợt 1) ——
            "Reels": "Reels",
            "Follow": "Seguir",
            "Following": "Seguindo",
            "New video": "Novo vídeo",
            "Post video": "Publicar vídeo",
            "Description": "Descrição",
            "Choose video": "Escolher vídeo",
            "Add friend": "Adicionar amigo",
            "Accept": "Aceitar",
            "Decline": "Recusar",
            "Request sent": "Pedido enviado",
            "Your ID": "Seu ID",
            "No friends yet": "Ainda sem amigos",
            "Tap to message": "Toque para mensagem",
            "Requests": "Pedidos",
            "Media Converter": "Conversor de mídia",
            "Create link": "Criar link",
            "Result link": "Link do resultado",
            "Format": "Formato",
            "Output format": "Formato de saída",
            "Guide": "Guia",
            "Link history": "Histórico de links",
            "Clear all": "Limpar tudo",
            "Choose image or video": "Escolher imagem ou vídeo",
            "Uploading...": "Enviando...",
            "Processing...": "Processando...",
            "Social":               "Social",
            "Video":                "Vídeo",
            "Store":                "Loja",
            "Friends":              "Amigos",
            "Explore":              "Explorar",
            "Login":                "Entrar",
            "Register":             "Cadastrar",
            "Save":                 "Salvar",
            "Cancel":               "Cancelar",
            "Delete":               "Excluir",
            "Edit":                 "Editar",
            "Close":                "Fechar",
            "Back":                 "Voltar",
            "Done":                 "Concluir",
            "Confirm":              "Confirmar",
            "Search":               "Pesquisar",
            "Send":                 "Enviar",
            "Add":                  "Adicionar",
            "Remove":               "Remover",
            "Share":                "Compartilhar",
            "Copy":                 "Copiar",
            "Logout":               "Sair",
            "Settings":             "Configurações",
            "Admin":                "Admin",
            "Profile":              "Perfil",
            "Home":                 "Início",
            "Next":                 "Próximo",
            "Continue":             "Continuar",
            "Retry":                "Tentar novamente",
            "Language & Appearance": "Idioma e aparência",
            "Language":             "Idioma",
            "Theme":                "Tema",
            "Light":                "Claro",
            "Dark":                 "Escuro",
            "Auto":                 "Auto",
            "App logo & effects":   "Logo e efeitos",
            "Color effect":         "Efeito de cor",
            "Font":                 "Fonte",
            "Animation":            "Animação",
            "Cart":                 "Carrinho",
            "Checkout":             "Finalizar",
            "Buy":                  "Comprar",
            "Price":                "Preço",
            "Discount":             "Desconto",
            "Product":              "Produto",
            "Category":             "Categoria",
            "Order":                "Pedido",
            "Payment":              "Pagamento",
            "Balance":              "Saldo",
            "Wallet":               "Carteira",
            "Top up":               "Recarregar",
            "Purchase history":     "Histórico",
            "Review":               "Avaliação",
            "Rating":               "Classificação",
            "Loading...":           "Carregando...",
            "Error":                "Erro",
            "Success":              "Sucesso",
            "Failed":               "Falhou",
            "Connecting...":        "Conectando...",
            "Connected":            "Conectado",
            "Disconnected":         "Desconectado",
            "Messages":             "Mensagens",
            "Notifications":        "Notificações",
            "Online":               "Online",
            "Offline":              "Offline",
            "Entertainment":        "Entretenimento",
            "Library":              "Biblioteca",
            "Tools":                "Ferramentas",
            "Games":                "Jogos",
            "Converter":            "Conversor",
        ],

        // ──────────────── Russian ────────────────
        "ru": [
            // —— Đăng nhập/Ví/Thanh toán (đợt 3) ——
            "Password": "Пароль",
            "Forgot password?": "Забыли пароль?",
            "or": "или",
            "Create new account": "Создать аккаунт",
            "Create account": "Создать аккаунт",
            "Change": "Изменить",
            "Server": "Сервер",
            "Change password": "Сменить пароль",
            "Top up wallet": "Пополнить кошелёк",
            "Wallet history": "История кошелька",
            "Purchase": "Покупка",
            "Bank": "Банк",
            "Account number": "Номер счёта",
            "Account holder": "Владелец счёта",
            "Transfer note": "Назначение",
            "Amount": "Сумма",
            "Upgrade to PRO": "Перейти на PRO",
            "Upgrade to Pro": "Перейти на Pro",
            "Pro feature": "Функция Pro",
            "Pending": "Ожидание",
            "Credited": "Зачислено",
            "Username": "Имя пользователя",
            // —— Cửa hàng & Cài đặt (đợt 2) ——
            "Store wallet": "Кошелёк",
            "Wallet balance": "Баланс",
            "Downloads": "Загрузки",
            "Download": "Скачать",
            "All products": "Все товары",
            "Sort": "Сортировка",
            "Filter": "Фильтр",
            "Default": "По умолчанию",
            "In stock only": "Только в наличии",
            "Out of stock": "Нет в наличии",
            "Wishlist": "Избранное",
            "Recently viewed": "Недавние",
            "Add to cart": "В корзину",
            "Total": "Итого",
            "Subtotal": "Подытог",
            "Pay": "Оплатить",
            "Promo code": "Промокод",
            "Apply": "Применить",
            "My orders": "Мои заказы",
            "Account": "Аккаунт",
            "Status": "Статус",
            "Plan": "Тариф",
            "Save changes": "Сохранить",
            "Choose a plan": "Выбрать тариф",
            "Rate this product": "Оценить товар",
            "Contact seller": "Связаться с продавцом",
            // —— Bổ sung đa ngôn ngữ (đợt 1) ——
            "Reels": "Рилсы",
            "Follow": "Подписаться",
            "Following": "Вы подписаны",
            "New video": "Новое видео",
            "Post video": "Опубликовать",
            "Description": "Описание",
            "Choose video": "Выбрать видео",
            "Add friend": "Добавить друга",
            "Accept": "Принять",
            "Decline": "Отклонить",
            "Request sent": "Запрос отправлен",
            "Your ID": "Ваш ID",
            "No friends yet": "Пока нет друзей",
            "Tap to message": "Нажмите, чтобы написать",
            "Requests": "Запросы",
            "Media Converter": "Конвертер медиа",
            "Create link": "Создать ссылку",
            "Result link": "Ссылка-результат",
            "Format": "Формат",
            "Output format": "Формат вывода",
            "Guide": "Руководство",
            "Link history": "История ссылок",
            "Clear all": "Очистить всё",
            "Choose image or video": "Выбрать фото или видео",
            "Uploading...": "Загрузка...",
            "Processing...": "Обработка...",
            "Social":               "Социальный",
            "Video":                "Видео",
            "Store":                "Магазин",
            "Friends":              "Друзья",
            "Explore":              "Обзор",
            "Login":                "Войти",
            "Register":             "Регистрация",
            "Save":                 "Сохранить",
            "Cancel":               "Отмена",
            "Delete":               "Удалить",
            "Edit":                 "Изменить",
            "Close":                "Закрыть",
            "Back":                 "Назад",
            "Done":                 "Готово",
            "Confirm":              "Подтвердить",
            "Search":               "Поиск",
            "Send":                 "Отправить",
            "Add":                  "Добавить",
            "Remove":               "Убрать",
            "Share":                "Поделиться",
            "Copy":                 "Копировать",
            "Logout":               "Выйти",
            "Settings":             "Настройки",
            "Admin":                "Администратор",
            "Profile":              "Профиль",
            "Home":                 "Главная",
            "Next":                 "Далее",
            "Continue":             "Продолжить",
            "Retry":                "Повторить",
            "Language & Appearance": "Язык и внешний вид",
            "Language":             "Язык",
            "Theme":                "Тема",
            "Light":                "Светлая",
            "Dark":                 "Тёмная",
            "Auto":                 "Авто",
            "App logo & effects":   "Лого и эффекты",
            "Color effect":         "Цветовой эффект",
            "Font":                 "Шрифт",
            "Animation":            "Анимация",
            "Cart":                 "Корзина",
            "Checkout":             "Оплата",
            "Buy":                  "Купить",
            "Price":                "Цена",
            "Discount":             "Скидка",
            "Product":              "Товар",
            "Category":             "Категория",
            "Order":                "Заказ",
            "Payment":              "Оплата",
            "Balance":              "Баланс",
            "Wallet":               "Кошелёк",
            "Top up":               "Пополнить",
            "Purchase history":     "История покупок",
            "Review":               "Отзыв",
            "Rating":               "Рейтинг",
            "Loading...":           "Загрузка...",
            "Error":                "Ошибка",
            "Success":              "Успешно",
            "Failed":               "Не удалось",
            "Connecting...":        "Подключение...",
            "Connected":            "Подключено",
            "Disconnected":         "Отключено",
            "Messages":             "Сообщения",
            "Notifications":        "Уведомления",
            "Online":               "Онлайн",
            "Offline":              "Офлайн",
            "Entertainment":        "Развлечения",
            "Library":              "Библиотека",
            "Tools":                "Инструменты",
            "Games":                "Игры",
            "Converter":            "Конвертер",
        ],

        // ──────────────── Indonesian / Bahasa ────────────────
        "id": [
            // —— Đăng nhập/Ví/Thanh toán (đợt 3) ——
            "Password": "Kata sandi",
            "Forgot password?": "Lupa kata sandi?",
            "or": "atau",
            "Create new account": "Buat akun baru",
            "Create account": "Buat akun",
            "Change": "Ubah",
            "Server": "Server",
            "Change password": "Ubah kata sandi",
            "Top up wallet": "Isi dompet",
            "Wallet history": "Riwayat dompet",
            "Purchase": "Pembelian",
            "Bank": "Bank",
            "Account number": "Nomor rekening",
            "Account holder": "Pemilik rekening",
            "Transfer note": "Catatan transfer",
            "Amount": "Jumlah",
            "Upgrade to PRO": "Tingkatkan ke PRO",
            "Upgrade to Pro": "Tingkatkan ke Pro",
            "Pro feature": "Fitur Pro",
            "Pending": "Menunggu",
            "Credited": "Dikreditkan",
            "Username": "Nama pengguna",
            // —— Cửa hàng & Cài đặt (đợt 2) ——
            "Store wallet": "Dompet toko",
            "Wallet balance": "Saldo",
            "Downloads": "Unduhan",
            "Download": "Unduh",
            "All products": "Semua produk",
            "Sort": "Urutkan",
            "Filter": "Saring",
            "Default": "Default",
            "In stock only": "Hanya tersedia",
            "Out of stock": "Habis",
            "Wishlist": "Favorit",
            "Recently viewed": "Baru dilihat",
            "Add to cart": "Tambah ke keranjang",
            "Total": "Total",
            "Subtotal": "Subtotal",
            "Pay": "Bayar",
            "Promo code": "Kode promo",
            "Apply": "Terapkan",
            "My orders": "Pesanan saya",
            "Account": "Akun",
            "Status": "Status",
            "Plan": "Paket",
            "Save changes": "Simpan perubahan",
            "Choose a plan": "Pilih paket",
            "Rate this product": "Nilai produk",
            "Contact seller": "Hubungi penjual",
            // —— Bổ sung đa ngôn ngữ (đợt 1) ——
            "Reels": "Reels",
            "Follow": "Ikuti",
            "Following": "Mengikuti",
            "New video": "Video baru",
            "Post video": "Posting video",
            "Description": "Deskripsi",
            "Choose video": "Pilih video",
            "Add friend": "Tambah teman",
            "Accept": "Terima",
            "Decline": "Tolak",
            "Request sent": "Permintaan terkirim",
            "Your ID": "ID Anda",
            "No friends yet": "Belum ada teman",
            "Tap to message": "Ketuk untuk pesan",
            "Requests": "Permintaan",
            "Media Converter": "Konversi media",
            "Create link": "Buat tautan",
            "Result link": "Tautan hasil",
            "Format": "Format",
            "Output format": "Format keluaran",
            "Guide": "Panduan",
            "Link history": "Riwayat tautan",
            "Clear all": "Hapus semua",
            "Choose image or video": "Pilih gambar/video",
            "Uploading...": "Mengunggah...",
            "Processing...": "Memproses...",
            "Social":               "Sosial",
            "Video":                "Video",
            "Store":                "Toko",
            "Friends":              "Teman",
            "Explore":              "Jelajahi",
            "Login":                "Masuk",
            "Register":             "Daftar",
            "Save":                 "Simpan",
            "Cancel":               "Batal",
            "Delete":               "Hapus",
            "Edit":                 "Edit",
            "Close":                "Tutup",
            "Back":                 "Kembali",
            "Done":                 "Selesai",
            "Confirm":              "Konfirmasi",
            "Search":               "Cari",
            "Send":                 "Kirim",
            "Add":                  "Tambah",
            "Remove":               "Hapus",
            "Share":                "Bagikan",
            "Copy":                 "Salin",
            "Logout":               "Keluar",
            "Settings":             "Pengaturan",
            "Admin":                "Admin",
            "Profile":              "Profil",
            "Home":                 "Beranda",
            "Next":                 "Berikutnya",
            "Continue":             "Lanjutkan",
            "Retry":                "Coba lagi",
            "Language & Appearance": "Bahasa & Tampilan",
            "Language":             "Bahasa",
            "Theme":                "Tema",
            "Light":                "Terang",
            "Dark":                 "Gelap",
            "Auto":                 "Otomatis",
            "App logo & effects":   "Logo & Efek",
            "Color effect":         "Efek warna",
            "Font":                 "Font",
            "Animation":            "Animasi",
            "Cart":                 "Keranjang",
            "Checkout":             "Bayar",
            "Buy":                  "Beli",
            "Price":                "Harga",
            "Discount":             "Diskon",
            "Product":              "Produk",
            "Category":             "Kategori",
            "Order":                "Pesanan",
            "Payment":              "Pembayaran",
            "Balance":              "Saldo",
            "Wallet":               "Dompet",
            "Top up":               "Isi ulang",
            "Purchase history":     "Riwayat",
            "Review":               "Ulasan",
            "Rating":               "Penilaian",
            "Loading...":           "Memuat...",
            "Error":                "Kesalahan",
            "Success":              "Berhasil",
            "Failed":               "Gagal",
            "Connecting...":        "Menghubungkan...",
            "Connected":            "Terhubung",
            "Disconnected":         "Terputus",
            "Messages":             "Pesan",
            "Notifications":        "Notifikasi",
            "Online":               "Online",
            "Offline":              "Offline",
            "Entertainment":        "Hiburan",
            "Library":              "Perpustakaan",
            "Tools":                "Alat",
            "Games":                "Game",
            "Converter":            "Konverter",
        ],

        // ──────────────── Arabic ────────────────
        "ar": [
            // —— Đăng nhập/Ví/Thanh toán (đợt 3) ——
            "Password": "كلمة المرور",
            "Forgot password?": "نسيت كلمة المرور؟",
            "or": "أو",
            "Create new account": "إنشاء حساب جديد",
            "Create account": "إنشاء حساب",
            "Change": "تغيير",
            "Server": "الخادم",
            "Change password": "تغيير كلمة المرور",
            "Top up wallet": "شحن المحفظة",
            "Wallet history": "سجل المحفظة",
            "Purchase": "شراء",
            "Bank": "البنك",
            "Account number": "رقم الحساب",
            "Account holder": "صاحب الحساب",
            "Transfer note": "ملاحظة التحويل",
            "Amount": "المبلغ",
            "Upgrade to PRO": "الترقية إلى PRO",
            "Upgrade to Pro": "الترقية إلى Pro",
            "Pro feature": "ميزة Pro",
            "Pending": "قيد الانتظار",
            "Credited": "تمت الإضافة",
            "Username": "اسم المستخدم",
            // —— Cửa hàng & Cài đặt (đợt 2) ——
            "Store wallet": "محفظة المتجر",
            "Wallet balance": "الرصيد",
            "Downloads": "التنزيلات",
            "Download": "تنزيل",
            "All products": "كل المنتجات",
            "Sort": "ترتيب",
            "Filter": "تصفية",
            "Default": "افتراضي",
            "In stock only": "المتوفر فقط",
            "Out of stock": "نفد المخزون",
            "Wishlist": "المفضلة",
            "Recently viewed": "شوهد مؤخرًا",
            "Add to cart": "أضف للسلة",
            "Total": "الإجمالي",
            "Subtotal": "المجموع الفرعي",
            "Pay": "ادفع",
            "Promo code": "رمز ترويجي",
            "Apply": "تطبيق",
            "My orders": "طلباتي",
            "Account": "الحساب",
            "Status": "الحالة",
            "Plan": "الخطة",
            "Save changes": "حفظ التغييرات",
            "Choose a plan": "اختر خطة",
            "Rate this product": "قيّم المنتج",
            "Contact seller": "تواصل مع البائع",
            // —— Bổ sung đa ngôn ngữ (đợt 1) ——
            "Reels": "ريلز",
            "Follow": "متابعة",
            "Following": "تتابع",
            "New video": "فيديو جديد",
            "Post video": "نشر الفيديو",
            "Description": "الوصف",
            "Choose video": "اختر فيديو",
            "Add friend": "إضافة صديق",
            "Accept": "قبول",
            "Decline": "رفض",
            "Request sent": "تم إرسال الطلب",
            "Your ID": "معرّفك",
            "No friends yet": "لا أصدقاء بعد",
            "Tap to message": "اضغط للمراسلة",
            "Requests": "الطلبات",
            "Media Converter": "محوّل الوسائط",
            "Create link": "إنشاء رابط",
            "Result link": "رابط النتيجة",
            "Format": "الصيغة",
            "Output format": "صيغة الإخراج",
            "Guide": "دليل",
            "Link history": "سجل الروابط",
            "Clear all": "مسح الكل",
            "Choose image or video": "اختر صورة أو فيديو",
            "Uploading...": "جارٍ الرفع...",
            "Processing...": "جارٍ المعالجة...",
            "Social":               "اجتماعي",
            "Video":                "فيديو",
            "Store":                "متجر",
            "Friends":              "أصدقاء",
            "Explore":              "استكشاف",
            "Login":                "تسجيل الدخول",
            "Register":             "التسجيل",
            "Save":                 "حفظ",
            "Cancel":               "إلغاء",
            "Delete":               "حذف",
            "Edit":                 "تعديل",
            "Close":                "إغلاق",
            "Back":                 "رجوع",
            "Done":                 "تم",
            "Confirm":              "تأكيد",
            "Search":               "بحث",
            "Send":                 "إرسال",
            "Add":                  "إضافة",
            "Remove":               "إزالة",
            "Share":                "مشاركة",
            "Copy":                 "نسخ",
            "Logout":               "تسجيل الخروج",
            "Settings":             "الإعدادات",
            "Admin":                "مسؤول",
            "Profile":              "الملف الشخصي",
            "Home":                 "الرئيسية",
            "Next":                 "التالي",
            "Continue":             "متابعة",
            "Retry":                "إعادة المحاولة",
            "Language & Appearance": "اللغة والمظهر",
            "Language":             "اللغة",
            "Theme":                "السمة",
            "Light":                "فاتح",
            "Dark":                 "داكن",
            "Auto":                 "تلقائي",
            "App logo & effects":   "الشعار والتأثيرات",
            "Color effect":         "تأثير الألوان",
            "Font":                 "الخط",
            "Animation":            "الرسوم المتحركة",
            "Cart":                 "سلة التسوق",
            "Checkout":             "الدفع",
            "Buy":                  "شراء",
            "Price":                "السعر",
            "Discount":             "خصم",
            "Product":              "منتج",
            "Category":             "فئة",
            "Order":                "طلب",
            "Payment":              "دفع",
            "Balance":              "الرصيد",
            "Wallet":               "المحفظة",
            "Top up":               "شحن",
            "Purchase history":     "سجل الشراء",
            "Review":               "مراجعة",
            "Rating":               "تقييم",
            "Loading...":           "جار التحميل...",
            "Error":                "خطأ",
            "Success":              "نجاح",
            "Failed":               "فشل",
            "Connecting...":        "جار الاتصال...",
            "Connected":            "متصل",
            "Disconnected":         "منقطع",
            "Messages":             "الرسائل",
            "Notifications":        "الإشعارات",
            "Online":               "متصل",
            "Offline":              "غير متصل",
            "Entertainment":        "ترفيه",
            "Library":              "مكتبة",
            "Tools":                "أدوات",
            "Games":                "ألعاب",
            "Converter":            "محول",
        ],

        // ──────────────── Hindi ────────────────
        "hi": [
            // —— Đăng nhập/Ví/Thanh toán (đợt 3) ——
            "Password": "पासवर्ड",
            "Forgot password?": "पासवर्ड भूल गए?",
            "or": "या",
            "Create new account": "नया खाता बनाएँ",
            "Create account": "खाता बनाएँ",
            "Change": "बदलें",
            "Server": "सर्वर",
            "Change password": "पासवर्ड बदलें",
            "Top up wallet": "वॉलेट टॉप अप",
            "Wallet history": "वॉलेट इतिहास",
            "Purchase": "खरीद",
            "Bank": "बैंक",
            "Account number": "खाता संख्या",
            "Account holder": "खाताधारक",
            "Transfer note": "ट्रांसफ़र नोट",
            "Amount": "राशि",
            "Upgrade to PRO": "PRO में अपग्रेड",
            "Upgrade to Pro": "Pro में अपग्रेड",
            "Pro feature": "Pro सुविधा",
            "Pending": "लंबित",
            "Credited": "जमा किया",
            "Username": "उपयोगकर्ता नाम",
            // —— Cửa hàng & Cài đặt (đợt 2) ——
            "Store wallet": "स्टोर वॉलेट",
            "Wallet balance": "वॉलेट शेष",
            "Downloads": "डाउनलोड",
            "Download": "डाउनलोड",
            "All products": "सभी उत्पाद",
            "Sort": "क्रमबद्ध",
            "Filter": "फ़िल्टर",
            "Default": "डिफ़ॉल्ट",
            "In stock only": "केवल स्टॉक में",
            "Out of stock": "स्टॉक खत्म",
            "Wishlist": "पसंद",
            "Recently viewed": "हाल में देखा",
            "Add to cart": "कार्ट में जोड़ें",
            "Total": "कुल",
            "Subtotal": "उप-योग",
            "Pay": "भुगतान",
            "Promo code": "प्रोमो कोड",
            "Apply": "लागू करें",
            "My orders": "मेरे ऑर्डर",
            "Account": "खाता",
            "Status": "स्थिति",
            "Plan": "प्लान",
            "Save changes": "बदलाव सहेजें",
            "Choose a plan": "प्लान चुनें",
            "Rate this product": "उत्पाद रेट करें",
            "Contact seller": "विक्रेता से संपर्क",
            // —— Bổ sung đa ngôn ngữ (đợt 1) ——
            "Reels": "रील्स",
            "Follow": "फ़ॉलो",
            "Following": "फ़ॉलो किया",
            "New video": "नया वीडियो",
            "Post video": "वीडियो पोस्ट करें",
            "Description": "विवरण",
            "Choose video": "वीडियो चुनें",
            "Add friend": "मित्र जोड़ें",
            "Accept": "स्वीकारें",
            "Decline": "अस्वीकारें",
            "Request sent": "अनुरोध भेजा गया",
            "Your ID": "आपकी आईडी",
            "No friends yet": "अभी कोई मित्र नहीं",
            "Tap to message": "मैसेज के लिए टैप करें",
            "Requests": "अनुरोध",
            "Media Converter": "मीडिया कन्वर्टर",
            "Create link": "लिंक बनाएँ",
            "Result link": "परिणाम लिंक",
            "Format": "प्रारूप",
            "Output format": "आउटपुट प्रारूप",
            "Guide": "गाइड",
            "Link history": "लिंक इतिहास",
            "Clear all": "सब हटाएँ",
            "Choose image or video": "छवि या वीडियो चुनें",
            "Uploading...": "अपलोड हो रहा...",
            "Processing...": "प्रोसेस हो रहा...",
            "Social":               "सोशल",
            "Video":                "वीडियो",
            "Store":                "स्टोर",
            "Friends":              "दोस्त",
            "Explore":              "एक्सप्लोर",
            "Login":                "लॉगिन",
            "Register":             "रजिस्टर",
            "Save":                 "सेव करें",
            "Cancel":               "रद्द करें",
            "Delete":               "हटाएं",
            "Edit":                 "संपादित करें",
            "Close":                "बंद करें",
            "Back":                 "वापस",
            "Done":                 "हो गया",
            "Confirm":              "पुष्टि करें",
            "Search":               "खोजें",
            "Send":                 "भेजें",
            "Add":                  "जोड़ें",
            "Remove":               "हटाएं",
            "Share":                "शेयर करें",
            "Copy":                 "कॉपी करें",
            "Logout":               "लॉगआउट",
            "Settings":             "सेटिंग्स",
            "Admin":                "एडमिन",
            "Profile":              "प्रोफाइल",
            "Home":                 "होम",
            "Next":                 "अगला",
            "Continue":             "जारी रखें",
            "Retry":                "फिर से प्रयास करें",
            "Language & Appearance": "भाषा और रूप",
            "Language":             "भाषा",
            "Theme":                "थीम",
            "Light":                "लाइट",
            "Dark":                 "डार्क",
            "Auto":                 "ऑटो",
            "App logo & effects":   "लोगो और प्रभाव",
            "Color effect":         "रंग प्रभाव",
            "Font":                 "फ़ॉन्ट",
            "Animation":            "एनिमेशन",
            "Cart":                 "कार्ट",
            "Checkout":             "चेकआउट",
            "Buy":                  "खरीदें",
            "Price":                "कीमत",
            "Discount":             "छूट",
            "Product":              "उत्पाद",
            "Category":             "श्रेणी",
            "Order":                "ऑर्डर",
            "Payment":              "भुगतान",
            "Balance":              "शेष",
            "Wallet":               "वॉलेट",
            "Top up":               "टॉप अप",
            "Purchase history":     "खरीद इतिहास",
            "Review":               "समीक्षा",
            "Rating":               "रेटिंग",
            "Loading...":           "लोड हो रहा है...",
            "Error":                "त्रुटि",
            "Success":              "सफलता",
            "Failed":               "विफल",
            "Connecting...":        "कनेक्ट हो रहा है...",
            "Connected":            "कनेक्टेड",
            "Disconnected":         "डिस्कनेक्टेड",
            "Messages":             "संदेश",
            "Notifications":        "सूचनाएं",
            "Online":               "ऑनलाइन",
            "Offline":              "ऑफलाइन",
            "Entertainment":        "मनोरंजन",
            "Library":              "लाइब्रेरी",
            "Tools":                "टूल्स",
            "Games":                "गेम्स",
            "Converter":            "कनवर्टर",
        ],
    ]
}
