disabled_rules:
  - trailing_whitespace
  - todo
opt_in_rules:
  - empty_count
  - closure_spacing
  - explicit_init
excluded:
  - Tests
  - RemoteDesktop.docc
line_length:
  warning: 140
  error: 200
type_body_length:
  warning: 400
file_length:
  warning: 600
identifier_name:
  min_length: 1
  excluded: [id, x, y, e, f, dx, dy]
