services:
  guacd:
    image: guacamole/guacd:1.5.5
    container_name: kenios_guacd
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: kenios_guac_db
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  guacamole:
    image: guacamole/guacamole:1.5.5
    container_name: kenios_guacamole
    depends_on:
      - guacd
      - postgres
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USER: guacamole_user
      POSTGRESQL_PASSWORD: ${DB_PASSWORD}
      # Bỏ tiền tố ngữ cảnh để mở thẳng /  (tuỳ chọn)
      WEBAPP_CONTEXT: ROOT
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
